<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="QuickParrot.Input.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuickParrot.Core\QuickParrot.Core.csproj" />
  </ItemGroup>

</Project>
