<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuickParrot.Audio\QuickParrot.Audio.csproj" />
    <ProjectReference Include="..\QuickParrot.Core\QuickParrot.Core.csproj" />
    <ProjectReference Include="..\QuickParrot.Input\QuickParrot.Input.csproj" />
    <ProjectReference Include="..\QuickParrot.Overlay\QuickParrot.Overlay.csproj" />
  </ItemGroup>

</Project>
